# This is a basic workflow to help you get started with Actions

name: Telegram

# Controls when the workflow will run
on:
  # Triggers the workflow when issue is closed
  issues:
    types:
      - closed

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

jobs:

  # This will send message to Telegram
  telegram-notify:
    name: Send notification to Telegram — Python
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python v${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Python version
        run: python3 --version

      - name: Parse Github issue & Send notification to Telegram
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          GITHUB_ISSUE_BODY: ${{ github.event.issue.body }}
          TELEGRAM_MESSAGE_TEMPLATE: ☑️ Тикет [${{ github.event.issue.title }}](${{ github.event.issue.html_url }}) закрыт
          TELEGRAM_PARSE_MODE: MarkdownV2
          TELEGRAM_ALLOW_SENDING_WITHOUT_REPLY: True
        run: python3 send_telegram.py
